# Generated by Django 2.2.5 on 2020-02-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='attendance_date',
            field=models.DateField(default='<jamming-date>'),
        ),
    ]
