# Generated by Django 2.2.5 on 2020-01-26 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectallocation',
            name='subjects',
        ),
        migrations.AddField(
            model_name='subjectallocation',
            name='subjects',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='allocated_subjects', to='DB.Subject'),
            preserve_default=False,
        ),
    ]
