# Generated by Django 2.2.5 on 2020-02-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='end_date',
            field=models.DateField(blank=True, default='2020-10-2'),
            preserve_default=False,
        ),
    ]
