# Generated by Django 2.2.5 on 2020-02-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0002_auto_20200223_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='school_logo',
            field=models.ImageField(blank=True, null=True, upload_to='school_info'),
        ),
        migrations.AddField(
            model_name='school',
            name='telephone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
