# Generated by Django 2.2.5 on 2020-01-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0003_teacher_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(default='+254', max_length=25),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
