# Generated by Django 2.2.5 on 2020-02-12 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0003_auto_20200212_1202'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentattendance',
            name='status',
        ),
        migrations.RemoveField(
            model_name='studentattendance',
            name='student',
        ),
        migrations.DeleteModel(
            name='AttendanceStatus',
        ),
        migrations.DeleteModel(
            name='StudentAttendance',
        ),
    ]
