# Generated by Django 2.2.5 on 2020-01-29 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0006_auto_20200129_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='signed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB.Teacher'),
        ),
    ]
