# Generated by Django 2.2.5 on 2020-01-29 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0007_auto_20200129_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='main_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_student', to='DB.ClassRoom'),
        ),
    ]
