# Generated by Django 2.2.5 on 2020-01-29 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0008_auto_20200129_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentclass',
            name='academic_year',
        ),
    ]
