# Generated by Django 2.2.5 on 2020-01-30 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0010_studentclass_academic_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationListHandler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_on_date', models.DateField()),
                ('ends_on_date', models.DateField()),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('comments', models.CharField(blank=True, help_text='Comments Regarding Exam', max_length=200, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('classrooms_affected', models.ManyToManyField(related_name='class_exams', to='DB.ClassRoom')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB.Teacher')),
            ],
        ),
    ]
