# Generated by Django 2.2.5 on 2020-01-10 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0010_auto_20200109_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_type',
            field=models.CharField(blank=True, choices=[('boarding school', 'boarding school'), ('day school', 'day school'), ('boarding-day school', 'boarding-day school')], max_length=25, null=True),
        ),
    ]
