# Generated by Django 2.2.5 on 2020-04-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0011_school_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='active',
            field=models.BooleanField(default=False, help_text='DANGER..!!!!!..If Marked this will be the default School Information System Wide...'),
        ),
    ]
