# Generated by Django 2.2.5 on 2020-01-10 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0011_school_school_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='classification',
            field=models.CharField(blank=True, choices=[('National', 'National'), ('Extra County', 'Extra County'), ('County', 'County'), ('Sub County', 'Sub County')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='ownership',
            field=models.CharField(blank=True, choices=[('Government', 'Government'), ('Private', 'Private')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='students_gender',
            field=models.CharField(blank=True, choices=[('Boys School', 'Boys School'), ('Girl School', 'Girl School'), ('Mixed', 'Mixed')], max_length=25, null=True),
        ),
    ]
