# Generated by Django 2.2.5 on 2020-01-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0013_dormitory_dormitoryallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='national_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
