# Generated by Django 2.2.5 on 2020-01-11 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0014_auto_20200111_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentparent',
            name='parent_name',
        ),
        migrations.RemoveField(
            model_name='studentparent',
            name='student_name',
        ),
        migrations.AddField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='DB.Parent'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ParentAddress',
        ),
        migrations.DeleteModel(
            name='StudentParent',
        ),
    ]
