# Generated by Django 2.2.5 on 2020-01-11 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0015_auto_20200111_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='class_stream',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_class', to='DB.Stream'),
        ),
    ]
