# Generated by Django 2.2.5 on 2020-02-26 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Day',
        ),
    ]
