# Generated by Django 2.2.5 on 2020-03-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_schoolevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolevent',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
