# Generated by Django 2.2.5 on 2020-03-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_schoolevent_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolevent',
            name='title',
            field=models.CharField(help_text='NB:  this is a system wide event service all events created willresults in system wide notification, \nFor personalised events go to noticeboard/Events', max_length=255),
        ),
    ]
