# Generated by Django 2.2.5 on 2020-03-24 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_auto_20200316_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolevent',
            old_name='end_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='schoolevent',
            old_name='start_date',
            new_name='start',
        ),
    ]
