# Generated by Django 2.2.5 on 2020-03-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_auto_20200326_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='markingperiod',
            name='sort_order',
            field=models.IntegerField(blank=True, help_text='The oder of the semester in this academic year ', null=True),
        ),
    ]
