# Generated by Django 2.2.5 on 2020-03-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_markingperiod_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markingperiod',
            name='sort_order',
            field=models.IntegerField(blank=True, help_text='The order of the semester in this academic year ', null=True),
        ),
    ]
