# Generated by Django 2.2.5 on 2020-04-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0020_auto_20200328_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='end_time',
            field=models.TimeField(unique=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='start_time',
            field=models.TimeField(unique=True),
        ),
    ]
