# Generated by Django 2.2.5 on 2020-04-22 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0024_auto_20200421_1549'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='departmentgraduationcredits',
            name='class_year',
        ),

        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DB.Department'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='DepartmentGraduationCredits',
        ),
    ]
