# Generated by Django 2.2.5 on 2020-04-22 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0027_auto_20200422_0830'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='period',
            unique_together={('name', 'start_time', 'end_time')},
        ),
    ]
