# Generated by Django 2.2.5 on 2020-01-03 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('long_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnrollmentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grades.Course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grades.Semester')),
            ],
        ),
        migrations.CreateModel(
            name='PermissionCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_code', models.IntegerField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.Section')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DB.Student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grades.Department'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grades.Section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DB.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('max_value', models.FloatField(default=100)),
                ('assign_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('a_cutoff', models.FloatField(blank=True, null=True)),
                ('b_cutoff', models.FloatField(blank=True, null=True)),
                ('c_cutoff', models.FloatField(blank=True, null=True)),
                ('d_cutoff', models.FloatField(blank=True, null=True)),
                ('assignment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grades.AssignmentType')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grades.Section')),
            ],
            options={
                'unique_together': {('section', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grades.EnrollmentStatus')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grades.Section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DB.Student')),
            ],
            options={
                'unique_together': {('section', 'student')},
            },
        ),
        migrations.CreateModel(
            name='AssignmentScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grades.Assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DB.Student')),
            ],
            options={
                'unique_together': {('student', 'assignment')},
            },
        ),
    ]
