# Generated by Django 2.2.5 on 2020-02-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0004_academicweek_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='week_days',
            field=models.ManyToManyField(to='DB.Day'),
        ),
        migrations.DeleteModel(
            name='AcademicWeek',
        ),
    ]
