# Generated by Django 2.2.5 on 2020-03-16 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0007_remove_academicyear_week_days'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolEvent',
        ),
    ]
