# Generated by Django 2.2.5 on 2020-03-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0009_remove_subject_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(default='1', max_length=250),
            preserve_default=False,
        ),
    ]
