# Generated by Django 2.2.5 on 2020-04-22 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0012_auto_20200402_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('order_rank', models.IntegerField(blank=True, help_text='Rank that courses will show up in reports', null=True)),
            ],
            options={
                'ordering': ('order_rank', 'name'),
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subject',
            name='graded',
            field=models.BooleanField(default=True, help_text='Teachers can submit grades for this course'),
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(blank=True, help_text='the department associated with this subject', null=True, on_delete=django.db.models.deletion.CASCADE, to='DB.Department'),
        ),
        migrations.CreateModel(
            name='DepartmentGraduationCredits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.DecimalField(decimal_places=2, max_digits=5, unique=True)),
                ('class_year', models.ForeignKey(help_text='Also applies to subsequent years unless a more recent requirement exists.', on_delete=django.db.models.deletion.CASCADE, to='DB.AcademicYear')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB.Department')),
            ],
            options={
                'unique_together': {('department', 'credits')},
            },
        ),
    ]
