# Generated by Django 2.2.5 on 2020-04-22 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0014_auto_20200422_0636'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartmentGraduationCredits',
        ),
    ]
