# Generated by Django 2.2.5 on 2020-02-12 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DB', '0004_auto_20200212_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='"Present" will not be saved but may show as a teacher option.', max_length=255, unique=True)),
                ('code', models.CharField(help_text='Short code used on attendance reports. Ex: A might be the code for the name Absent', max_length=10, unique=True)),
                ('teacher_selectable', models.BooleanField()),
                ('excused', models.BooleanField()),
                ('absent', models.BooleanField(help_text='Some statistics need to add various types of absent statuses, such as the number in parathesis in daily attendance')),
                ('tardy', models.BooleanField(help_text='Some statistics need to add various types of tardy statuses, such as the number in parathesis in daily attendance')),
                ('half', models.BooleanField(help_text='Half attendance when counting. DO NOT check off absent otherwise it will double count!')),
            ],
            options={
                'verbose_name_plural': 'Attendance Statuses',
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=150)),
                ('private_notes', models.CharField(blank=True, max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendance.AttendanceStatus')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance', to='DB.Student')),
            ],
            options={
                'ordering': ('-attendance_date', 'student'),
                'unique_together': {('student', 'attendance_date', 'status')},
            },
        ),
    ]
