# Generated by Django 2.2.5 on 2020-02-23 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
        ('DB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeComment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('override_final', models.BooleanField(help_text='Override final grade for making period instead of calculating it.')),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('letter_grade', models.CharField(blank=True, choices=[('I', 'Incomplete'), ('P', 'Pass'), ('F', 'Fail'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('HP', 'High Pass'), ('LP', 'Low Pass')], help_text='Will override grade', max_length=2, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Course')),
                ('marking_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.MarkingPeriod')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB.Student')),
            ],
            options={
                'unique_together': {('student', 'course', 'marking_period')},
            },
        ),
    ]
