# Generated by Django 2.2.5 on 2020-03-16 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0008_delete_schoolevent'),
        ('schedule', '0004_auto_20200316_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolevent',
            name='academic_year',
            field=models.ForeignKey(default='202', on_delete=django.db.models.deletion.CASCADE, to='DB.AcademicYear'),
            preserve_default=False,
        ),
    ]
