# Generated by Django 2.2.5 on 2020-03-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auto_20200316_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolevent',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
