# Generated by Django 2.2.5 on 2020-03-16 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0008_delete_schoolevent'),
        ('schedule', '0008_auto_20200316_1102'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schoolevent',
            unique_together={('title', 'academic_year')},
        ),
    ]
