# Generated by Django 2.2.5 on 2020-03-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_auto_20200316_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolevent',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolevent',
            name='start_date',
            field=models.DateField(),
        ),
    ]
