# Generated by Django 2.2.5 on 2020-03-28 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0009_remove_subject_short_name'),
        ('schedule', '0018_auto_20200328_1553'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseMeet',
            new_name='CoursePeriod',
        ),
    ]
