# Generated by Django 2.2.5 on 2020-03-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0019_auto_20200328_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='ignore_for_scheduling',
            field=models.BooleanField(default=False, help_text='if checked you can avoid period clash for scheduling a student'),
        ),
        migrations.AddField(
            model_name='period',
            name='short_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='period',
            name='sort_order',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='period',
            name='used_for_attendance',
            field=models.BooleanField(default=False, help_text='if marked a teacher would be able to take attendance for that particular period'),
        ),
    ]
