# Generated by Django 2.2.5 on 2020-04-21 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0022_auto_20200421_1544'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='period',
            unique_together={('name', 'start_time', 'end_time', 'sort_order')},
        ),
    ]
